version: '3.7'

services:
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    ports:
      - "6379:6379"

  mongodb:
    ports:
      - "27017:27017"
      
  postgres-db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "myPassw0rd"

  pgadmin:
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
