config:
  selfUrl: https://demomicro-st-gateway.eshoponabp.com
  corsOrigins: https://demomicro-st-admin.eshoponabp.com
  globalConfigurationBaseUrl: http://eshop-az-gateway-public
  authServer:
    authority: http://eshop-az-authserver
    requireHttpsMetadata: "false"
    swaggerClientId: WebGateway_Swagger
    swaggerClientSecret: "1q2w3e*"
  dotnetEnv: Production
  redisHost: redis-redis
  rabbitmqHost: rabbitmq-rabbitmq
  elasticsearchHost: elasticsearch-elasticsearch
ingress:
  host: demomicro-st-gateway.eshoponabp.com
image:
  repository: "volocr.azurecr.io/demomicro/gateway-web"
  tag: 1.0.1
reRoutes:
  accountService:
    url: http://eshop-az-authserver
  identityService:
    url: http://eshop-az-identity
  administrationService:
    url: http://eshop-az-administration
  catalogService:
    url: http://eshop-az-catalog
  orderingService:
    url: http://eshop-az-orderingv